### ISSUE TITLE
Most sulfurs appear to be missing

### ISSUE THREAD

**Issue by MuteTiefling** [klikli-dev/theurgy#193] opened 2024-06-30 13:13 UTC
**Describe the bug**
Most sulfurs appear to be missing. For example, I only see Wheat Sulfur in EMI. The sulfurs for raw ores are all missing. They're also missing from the book:

**Screenshots**
![image](https://github.com/klikli-dev/theurgy/assets/9543430/eb480c05-8109-4f6d-8da6-810e28579bb3)

**System (please complete the following information):**
- Theurgy Version: 1.24.1
- OS: Windows
- Minecraft Version: 1.21
- Modpack Link and Version, or list of mods: Enigmatica 10 in-dev

**Comment by klikli-dev** [comment] 2024-07-01 05:13
Thanks for reporting! I have to investigate, it might have to do with recipe conditions and loading changes in 1.21

Weird is that it can still render the name which I think this page automatically takes from the item ..

**Comment by klikli-dev** [comment] 2024-07-01 06:50
@MuteTiefling ok with "just" theurgy (my dev env) I cannot reproduce that, I can see all the vanilla-related sulfurs, both in JEI and in the book. Same if I additionally install EMI (book still works and the sulfurs show in EMI).

Could you attach a log? maybe that has some indicators

**Comment by amahlaka** [comment] 2024-07-01 09:04
I just noticed the same issue,
However, the sulfurs i have in my inventory such as iron and tin sulfurs are still there and render properly, but those don't show up in EMI.

And what is even weirder, is that the only item that i can insert into Liquefaction cauldron is Wheat, no other item is accepted when i right click it.
Also cant insert items into any of the other basic blocks such as calcination oven

**Comment by MuteTiefling** [comment] 2024-07-01 14:07
Yep, that's exactly how it presents for me.

Attached is a latest.log after launching the game. I've updated modonomicon as well from the initial report.

https://gist.github.com/MuteTiefling/5ca95d797e5787b83cd84c6d0bdeccd6

**Comment by MuteTiefling** [comment] 2024-07-01 14:10
This is the only thing that sticks out at me: 
`[01Jul2024 10:06:45.853] [Render thread/WARN] [Modonomicon/]: Recipe theurgy:calcination/alchemical_salt_strata_from_cobblestone (of type theurgy:calcination) not found.`

Is the rest of it dependant on this salt? All I have for strata salts are from clay and gravel:

![image](https://github.com/klikli-dev/theurgy/assets/9543430/f2c509d4-cde6-4842-95e6-aa13b3ef8c28)

**Comment by ImAK9** [comment] 2024-07-01 15:28
For some very odd reason, entirely deleting the /kubejs folder fixes this issue..
![image](https://github.com/klikli-dev/theurgy/assets/29925108/bcd11728-faef-469b-a79b-871373e7d354)
![image](https://github.com/klikli-dev/theurgy/assets/29925108/c5c98fe7-013f-4f3f-a193-6af9247362d5)

**Comment by klikli-dev** [comment] 2024-07-02 10:50
Thanks for the investigation! 
This was a KubeJS issue, fixed in https://github.com/KubeJS-Mods/KubeJS/commit/b8970fd4bd867da594952042bd3bd91b265115b3

Because it requires changes to the condition itself I have to mirror their changes in my fluid tag condition. I will leave the issue open until I implemented this in such a way that I can access kubejs data without a hard dependency on kubejs

**Comment by klikli-dev** [comment] 2024-07-02 11:27
Ok, going to add a temp fix for the fluid stuff and close this. Kubejs is working on a real solution for the issues related to tag modifications, if that needs theurgy changes too I will adopt them once available.

**Closed as completed by klikli-dev** 2024-07-02 11:27 UTC
Labels: bug
